name: oblt-cli/setup

description: |
  Setup oblt-cli for use in GitHub Actions workflows.

inputs:
  github-token:
    description: "The GitHub access token."
    required: true
  slack-channel:
    description: "The slack channel to notify the status."
    default: "#observablt-bots"
    required: false
  username:
    description: "Username to show in the deployments with oblt-cli, format: [a-z0-9]"
    default: "obltmachine"
    required: false
  version:
    description: "Install a specific version of oblt-cli"
    default: "7.2.2"
    required: false
  version-file:
    description: "The file to read the version from. E.g. `.oblt-cli-version` or `.tool-versions`. This option takes precedence over `version`."
    required: false

runs:
  using: composite
  steps:
    - name: Download oblt-cli and append to PATH
      run: ${{ github.action_path }}/download.sh
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        OBLT_CLI_VERSION: ${{ inputs.version }}
        OBLT_CLI_VERSION_FILE: ${{ inputs.version-file }}
      shell: bash
    - name: Configure oblt-cli
      run: >
        oblt-cli configure
        --git-http-mode
        --username="${OBLT_CLI_USERNAME}"
        --slack-channel="${OBLT_CLI_SLACK_CHANNEL}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ELASTIC_APM_ENVIRONMENT: ci
        OBLT_CLI_USERNAME: ${{ inputs.username }}
        OBLT_CLI_SLACK_CHANNEL: ${{ inputs.slack-channel }}
      shell: bash
    - name: Export env
      run: echo "ELASTIC_APM_ENVIRONMENT=ci" >> $GITHUB_ENV
      shell: bash
