# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle default oblt-cli version
    policy: ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version:0.3.0@sha256:663f7e73734fe86ced0e08787ee17215e192db56fd0fccd76358e7bc34dcd7b2
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/oblt-cli.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.9.1@sha256:5bbca67a9e31bf5432d5cae1452b9fc770014151ddd856f367ccb9ba46f6f8bb
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/update-compose.yml
  - name: Local Updatecli Policies
    config:
      - .ci/updatecli/
    values:
      - .ci/updatecli/values.d/scm.yml
