# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle default oblt-cli version
    policy: ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version:0.4.1@sha256:d982ec23e648fadd8936beec681e4c9154ad2090768fb8f6cbeff89863f6674f
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/oblt-cli.yml
  - name: Handle updatecli bumps
    policy: ghcr.io/elastic/oblt-updatecli-policies/updatecli/version:0.2.2@sha256:3c884a6a1004d383ac3747a5d400001be355ebca5d3e12749247a000b2221139
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/updatecli.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.10.0@sha256:588fb5b274c1e484198885723b5a67688416feeec414d41a33908826e448fd41
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/update-compose.yml
