# Config file for `updatecli compose ...`.
# https://www.updatecli.io/docs/core/compose/
policies:
  - name: Handle default oblt-cli version
    policy: ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version:0.3.0@sha256:663f7e73734fe86ced0e08787ee17215e192db56fd0fccd76358e7bc34dcd7b2
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/oblt-cli.yml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.10.0@sha256:588fb5b274c1e484198885723b5a67688416feeec414d41a33908826e448fd41
    values:
      - .ci/updatecli/values.d/scm.yml
      - .ci/updatecli/values.d/update-compose.yml
  - name: Local Updatecli Policies
    config:
      - .ci/updatecli/
    values:
      - .ci/updatecli/values.d/scm.yml
