name: 'Backport Action'
description: 'Automatically backport changes to specified branches based on PR labels'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
  backports_url:
    description: 'URL to fetch the backport branches configuration JSON'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      shell: bash
    
    - name: Run backport script
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PR_LABELS: ${{ toJSON(github.event.pull_request.labels) }}
        BACKPORTS_URL: ${{ inputs.backports_url }}
      run: python ${{ github.action_path }}/backport_script.py
      shell: bash
