name: 'github/project-add'

description: Tests if a GitHub user is a bot or not

inputs:
  github-token:
    description: 'The GitHub access token.'
    default: ${{ github.token }}
    required: true
  github-user:
    description: 'The GitHub username'
    required: true

outputs:
  result:
    description: "`true` if user is bot, `false` otherwise"
    value: ${{ steps.gh-api-user-type.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: add item to project
      id: gh-api-user-type
      run: |
        # will produce a 404 and non-zero when user does not exists
        type=$(gh api \
          -H "Accept: application/vnd.github+json" \
          /users/${{ env.GH_USER }} --jq .type )

        echo "::notice::GitHub user type = ${type}"

        if [[ 'Bot' == "${type}" ]]; then
          echo "result=true" >> "${GITHUB_OUTPUT}"
        else
          echo "result=false" >> "${GITHUB_OUTPUT}"
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_USER: ${{ inputs.github-user }}
