name: elastic/github-commands
description: Print the supported GitHub commands
inputs:
  github-token:
    description: 'The GitHub access token.'
    required: false
    type: string
    default: ${{ github.token }}
  continue-on-error:
    description: 'Whether to continue on error.'
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v8
      continue-on-error: true
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          let commands = `- \`run\` \`docs-build\` : Re-trigger the docs validation. (use unformatted text in the comment!)`
          // See https://github.com/elastic/logstash/pull/18383
          if ((context.repo.repo === 'logstash' || context.repo.repo === 'oblt-actions') && context.repo.owner === 'elastic') {
            commands += `
            - \`/run exhaustive tests\` : Run the exhaustive tests Buildkite pipeline.`
          }

          const body = `
            ### :robot: GitHub comments

            <details><summary>Expand to view the GitHub comments</summary>
            <p>

            Just comment with:
            ${commands}
            </p>
            </details>
          `.replace(/  +/g, '')
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })
