# action.yml
name: 'Mutex Action'
description: 'A simple locking/unlocking mechanism to provide mutual exclusion in Github Actions'
inputs:
  github-token:
    description: 'The token for accessing the repo.'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'The repository path that stores the lock (e.g `elastic/oblt-actions`).'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'The branch to use for the mutex'
    required: false
    default: 'mutex'
  internal_checkout-location:
    description: '[Internal] The location to store the mutex repo'
    required: false
    default: '${{ runner.temp }}/mutex/${{ github.run_id }}-${{ github.run_attempt }}/repo'
  suffix:
    description: 'Requester id suffix to avoid identical values for parallel/matrix jobs in the same workflow run'
    required: false
    default: 'default'
  timeout-minutes:
    description: 'Maximum time in minutes to wait for lock acquisition or release before timing out'
    required: false
    default: '30'
runs:
  using: 'node24'
  main: 'dist/lock/index.js'
  post: 'dist/unlock/index.js'
