name: maven/await-artifact
description: |
  Waits for an artifact to be available on maven central or the sonatype proxy maven central.
  With default values, we just wait for the publication to complete on `sonatype`, but the actual availability in maven central might not be ready yet.
  With `true`, we wait for the artifact to be published in maven central, this should be used when building other artifacts by downloading from maven central, which is for example quite common for docker images.
inputs:
  artifact-id:
    description: 'Maven artifact-ID of the artifact'
    required: true
  group-id:
    description: 'Maven group-ID of the artifact'
    required: true
  version:
    description: 'Version of the artifact to wait for'
    required: true
  sonatype-central:
    description: 'Whether to wait for the artifact to be available in the sonatype central repository.'
    default: true
    required: false
  maven-central:
    description: 'Whether to wait for the artifact to be available in the maven central repository.'
    default: false
    required: false
runs:
  using: "composite"
  steps:
    - name: Wait for artifact to be available on proxy sonatype maven central
      if: ${{ inputs.sonatype-central == 'true' }}
      shell: bash
      run: |
        TIME=30
        full_url="https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=${GROUP_ID}&a=${ARTIFACT_ID}&v=${VERSION}"
        until curl -fs -I -L "${full_url}" > /dev/null
        do
          echo "Artifact ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} not found on proxy maven central. Sleeping ${WAIT_SECONDS} seconds, retrying afterwards"
          sleep ${WAIT_SECONDS}s
        done
      env:
        ARTIFACT_ID: ${{ inputs.artifact-id }}
        GROUP_ID: ${{ inputs.group-id }}
        VERSION: ${{ inputs.version }}

    - name: Wait for artifact to be available on maven central
      if: ${{ inputs.maven-central == 'true' }}
      shell: bash
      run: |
        TIME=30
        GROUP_FOLDER="${GROUP_ID//.//}"
        full_url="https://repo.maven.apache.org/maven2/${GROUP_FOLDER}/${ARTIFACT_ID}/${VERSION}"
        until curl -fs -I -L "${full_url}" > /dev/null
        do
          echo "Artifact ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} not found on maven central. Sleeping ${WAIT_SECONDS} seconds, retrying afterwards"
          sleep ${WAIT_SECONDS}s
        done
      env:
        ARTIFACT_ID: ${{ inputs.artifact-id }}
        GROUP_ID: ${{ inputs.group-id }}
        VERSION: ${{ inputs.version }}
