name: maven/await-artifact
description: |
  Waits for an artifact to be available on maven central
inputs:
  artifact-id:
    description: 'Maven artifact-ID of the artifact'
    required: true
  group-id:
    description: 'Maven group-ID of the artifact'
    required: true
  version:
    description: 'Version of the artifact to wait for'
    required: true
runs:
  using: "composite"
  steps:
    - name: Wait for artifact to be available on maven central
      shell: bash
      run: |
        full_url="https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=${GROUP_ID}&a=${ARTIFACT_ID}&v=${VERSION}"
        until curl -fs -I -L "${full_url}" > /dev/null
        do
          echo "Artifact ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} not found on maven central. Sleeping 30 seconds, retrying afterwards"
          sleep 30s
        done
      env:
        ARTIFACT_ID: ${{ inputs.artifact-id }}
        GROUP_ID: ${{ inputs.group-id }}
        VERSION: ${{ inputs.version }}
