---
name: buildkite/run
description: A GitHub Action for triggering a build on a Buildkite pipeline.
inputs:
  org:
    description: 'Buildkite org to interact with.'
    default: elastic
    required: false
  token:
    description: 'Buildkite token.'
    required: true
  pipeline:
    description: 'Buildkite pipeline to interact with.'
    required: true
  wait-for:
    description: 'Whether to wait for the build to finish.'
    default: false
    required: false
  env-vars:
    description: 'Additional environment variables to set on the build.'
    required: false
  branch:
    description: 'Branch the commit belongs to. This allows you to take advantage of your pipeline and step-level branch filtering rules.'
    default: main
    required: false
  commit:
    description: 'Ref, SHA or tag to be built.'
    default: HEAD
    required: false
  message:
    description: 'The BK build message to be shown in the UI.'
    default: Triggered automatically with GH actions
    required: false

outputs:
  build:
    description: "The Buildkite build url"
    value: ${{ steps.trigger-buildkite.outputs.build }}
  number:
    description: "The Buildkite build number"
    value: ${{ steps.trigger-buildkite.outputs.number }}
  state:
    description: "The Buildkite build state"
    value: ${{ steps.trigger-buildkite.outputs.state }}

runs:
  using: "composite"
  steps:
    - id: trigger-buildkite
      name: Trigger Buildkite pipeline
      run: |
        ${{ github.action_path }}/run.sh \
          '${{ inputs.org }}' \
          '${{ inputs.pipeline }}' \
          '${{ inputs.env-vars }}' \
          '${{ inputs.wait-for }}' \
          '${{ inputs.token }}' \
          '${{ inputs.message }}' \
          '${{ inputs.commit }}' \
          '${{ inputs.branch }}'
      shell: bash

    - name: Cancel Buildkite pipeline
      if: cancelled() && inputs.wait-for && steps.trigger-buildkite.outputs.build_number
      run: |
        curl \
          --no-progress-meter \
          -H "Authorization: Bearer $BK_TOKEN" \
          -X "PUT" \
          "https://api.buildkite.com/v2/organizations/$ORG/pipelines/$PIPELINE/builds/$NUMBER/cancel"
      env:
        BK_TOKEN: ${{ inputs.token }}
        ORG: ${{ inputs.org }}
        PIPELINE: ${{ inputs.pipeline }}
        NUMBER: ${{ steps.trigger-buildkite.outputs.build_number }}
      shell: bash
