name: 'Backport Action'
description: 'Automatically backport changes to specified branches based on PR labels'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
  backports-url:
    description: 'URL to fetch the backport branches configuration JSON'
    required: true
    default: "https://storage.googleapis.com/artifacts-api/snapshots/branches.json"
  dry-run:
    description: 'Run in dry-run mode without creating comments'
    default: false
  test-pr-number:
    description: 'PR number to use in dry-run mode'
    required: false
    default: '9999'
  test-pr-labels:
    description: 'PR labels to use in dry-run mode (comma-separated)'
    required: false
    default: 'backport-active-all'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      shell: bash

    - name: Run backport script
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.dry-run == 'true' && inputs.test-pr-number || github.event.pull_request.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PR_LABELS: ${{ inputs.dry-run == 'true' && format('[{{"name":"{0}"}}]', inputs.test-pr-labels) || toJSON(github.event.pull_request.labels) }}
        BACKPORTS_URL: ${{ inputs.backports-url }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: python ${{ github.action_path }}/backport_script.py
      shell: bash
