---
name: 'version-framework'
description: Create matrix for the supported versions and frameworks

inputs:
  versions-file:
    description: 'The YAML file with the versions. Being VERSION the key for the list'
    required: true
  frameworks-file:
    description: 'The YAML file with the frameworks. Being FRAMEWORK the key for the list'
    required: true
  excluded-file:
    description: 'The YAML file with the excluded tuples. Being exclude the key for the list of tuples (VERSION, FRAMEWORK)'
    required: false

outputs:
  matrix:
    description: "Processed matrix with the required tuples of version and framework"
    value: ${{ steps.generator.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - id: generator
      run: python ${{ github.action_path }}/matrix.py
      env:
        VERSIONS_FILE: ${{ inputs.versions-file }}
        FRAMEWORKS_FILE: ${{ inputs.frameworks-file }}
        EXCLUDED_FILE: ${{ inputs.excluded-file }}
      shell: bash

    - name: debug
      run: |
        echo 'Matrix to test: ${{ steps.generator.outputs.matrix }}'
      shell: bash
