name: 'github/create-token'
description: Create ephemeral GitHub token

inputs:
  vault-instance:
    description: 'The Vault instance to use for GitHub token retrieval'
    default: "ci-prod"
    required: false
  # NOTE: upstream uses vault-role as input name, but we prefer token-policy for clarity
  token-policy:
    description: 'Vault role to assume for GitHub token retrieval if using wildcards in the subclaims.'
    required: false
  skip-token-revoke:
    description: 'If true, skip revoking the GitHub token on exit'
    required: false
    default: 'false'

outputs:
  token:
    description: "The GitHub ephemeral token"
    value: ${{ steps.fetch-token.outputs.token }}

runs:
  using: "composite"
  steps:
    - id: fetch-token
      uses: elastic/ci-gh-actions/fetch-github-token@v1.2.1
      with:
        vault-instance: ${{ inputs.vault-instance }}
        vault-role: ${{ inputs.token-policy }}
        skip-token-revoke: ${{ inputs.skip-token-revoke }}

    - name: Print rate limit for debugging
      continue-on-error: true
      if: runner.os != 'Windows'
      shell: bash
      run: |
        gh api /rate_limit | jq .
        env | sort
      env:
        GH_TOKEN: ${{ steps.fetch-token.outputs.token }}
        GH_PAGER: ''
