name: updatecli/install

description: |
  This is an opinionated GitHub Action to install the updatecli
runs:
  using: composite
  steps:
    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@8189f9f0e590d265fee517279fa4416eea5459ca # v2.62.0
