name: oblt/cli/cluster-destroy
description: 'Run the oblt-cli wrapper to destroy the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  cluster-info-file:
    description: 'The cluster info file (absolute path)'
    required: false
  github-token:
    description: 'The GitHub access token.'
    required: true
  username:
    description: 'Username to show in the deployments with oblt-cli, format: [a-z0-9]'
    default: 'obltmachine'
    required: false
runs:
  using: "composite"
  steps:
    - uses: elastic/oblt-actions/oblt-cli/cluster-name-validation@v1.9.2
      id: validation
      with:
        cluster-name: ${{ inputs.cluster-name }}
        cluster-info-file: ${{ inputs.cluster-info-file }}

    - uses: elastic/oblt-actions/oblt-cli/setup@v1.9.2
      with:
        github-token: ${{ inputs.github-token }}
        username: ${{ inputs.username }}
    - run: |
        oblt-cli cluster destroy --cluster-name "${{ steps.validation.outputs.cluster-name }}" --force
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
