---
name: buildkite/download
description: A GitHub Action for downloading artifacts from a Buildkite build.
inputs:
  token:
    description: 'Buildkite token.'
    required: true
  artifact-path:
    description: A file, directory or wildcard pattern that describes what to upload
    required: true
  org:
    description: 'Buildkite org to interact with.'
    default: elastic
    required: false
  pipeline:
    description: 'Buildkite pipeline to interact with.'
    required: true
  build:
    description: 'Buildkite pipeline build to interact with.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifacts
      run: |
        pip install globber==0.2.1
        python ${{ github.action_path }}/download_artifacts.py
      env:
        ARTIFACT_PATH: ${{ inputs.artifact-path }}
        BUILD_NUMBER: ${{ inputs.build }}
        ORG: ${{ inputs.org }}
        PIPELINE: ${{ inputs.pipeline }}
        BUILDKITE_API_ACCESS_TOKEN: ${{ inputs.token }}
      shell: bash
      