name: elastic/active-branches
description: |
  Fetch the current list of active branches in Elastic (the ones based on the Unified Release process)
inputs:
  exclude-branches:
    description: "Exclude branches comma separated"
    required: false
    default: ''
  filter-branches:
    description: "Whether to filter those branches that only exist in the github-repository"
    default: false
  github-token:
    description: 'The GitHub access token.'
    required: false
    default: ${{ github.token }}
  github-repository:
    description: 'The GitHub repository to search for active branches.'
    required: false
    default: ${{ github.repository }}

outputs:
  matrix:
    description: "Processed matrix with the branches (using the include format)"
    value: ${{ steps.generator.outputs.matrix }}
  branches:
    description: "Processed list of branches"
    value: ${{ steps.generator.outputs.branches }}
runs:
  using: composite
  steps:

    - name: Install Python dependencies
      run: |
        PIP=pip
        if command -v python3 >/dev/null 2>&1; then
          PIP=pip3
        fi
        ${PIP} install requests==2.31.0
      shell: bash

    - id: generator
      shell: bash
      run: |
        PYTHON=python
        if command -v python3 >/dev/null 2>&1; then
          PYTHON=python3
        fi
        ${PYTHON} "${{ github.action_path }}/script.py"
      env:
        EXCLUDE_BRANCHES: ${{ inputs.exclude-branches }}
        FILTER: ${{ inputs.filter-branches }}
        REPOSITORY: ${{ inputs.github-repository }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - id: debug
      shell: bash
      run: |
        echo 'Matrix: ${{ steps.generator.outputs.matrix }}'
