---
name: azure-auth
description: Authenticate to Azure using a service principal with OIDC.
author: Elastic Observability Team
inputs:
  subscriptionId:
    description: The Azure subscription ID to authenticate to.
    required: true
  tenantId:
    description: The Azure tenant ID.
    required: true
  clientId:
    description: The Azure client ID (Service Principal).
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.clientId }}
        tenant-id: ${{ inputs.tenantId }}
        subscription-id: ${{ inputs.subscriptionId }}

    - name: Set outputs
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          core.exportVariable('ARM_SUBSCRIPTION_ID', '${{ inputs.subscriptionId }}');
          core.exportVariable('ARM_TENANT_ID', '${{ inputs.tenantId }}');
          core.exportVariable('ARM_CLIENT_ID', '${{ inputs.clientId }}');
          core.exportVariable('ARM_USE_OIDC', 'true');
