name: slack/send

description: |
  This is an opinionated GitHub Action to send a message in slack.

inputs:
  bot-token:
    description: 'Specify the slack bot token.'
    required: true
  channel-id:
    description: 'Specify the slack channel-id.'
    required: true
  message:
    description: |-
      Slack message on Markdown format. Multiline messages must be escaped using URL encoding.
      https://github.com/orgs/community/discussions/26288

      This is an example how to escape a multiline message in Python:
      <pre>from urllib.parse import quote

      message = quote("""
      Hello!!!
      This is a multiline message
      """) # Multiline message</pre>
    required: true
  thread-timestamp:
    description: If you want to post a message as a threaded reply
    required: false
outputs:
  thread-timestamp:
    description: 'The timestamp on the message that was posted into Slack when using bot token'
    value: ${{ steps.slack_message.outputs.ts }}
runs:
  using: composite
  steps:
    - name: prepare message
      shell: python
      id: prepare
      env:
        MESSAGE: ${{ inputs.message }}
        CHANNEL_ID: ${{ inputs.channel-id }}
        THREAD_TS: ${{ inputs.thread-timestamp }}
      run: |
        # Prepare Slack API payload.
        # Documentation about the payload format.
        # https://api.slack.com/reference/messaging/payload
        # https://app.slack.com/block-kit-builder
        # https://api.slack.com/reference/surfaces/formatting
        # https://api.slack.com/reference/surfaces/formatting#escaping
        import os
        from urllib.parse import unquote
        import json

        if os.environ["MESSAGE"]:
          message = os.environ.get('MESSAGE', 'No message')
          message = unquote(message)
          message = '\n'.join(line.strip() for line in message.splitlines())
        else:
          raise Exception("message must be set.")

        print("message={}".format(message))

        payload = {
          "unfurl_links": False,
          "unfurl_media": False,
          "channel": os.environ.get('CHANNEL_ID'),
          "text": message,
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": message
              }
            }
          ]
        }

        thread_ts = os.environ.get('THREAD_TS', '')
        if thread_ts:
          payload["thread_ts"] = thread_ts

        payload_file = os.path.join(os.environ.get('RUNNER_TEMP', '/tmp'), 'slack_payload.json')
        with open(payload_file, 'w') as f:
          json.dump(payload, f)

        with open(os.environ.get('GITHUB_OUTPUT'), "a") as f:
          f.write("payload-file={}\n".format(payload_file))

    - uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
      id: slack_message
      with:
        method: chat.postMessage
        token: ${{ inputs.bot-token }}
        payload-file-path: ${{ steps.prepare.outputs.payload-file }}
