name: slack/send

description: |
  This is an opinionated GitHub Action to send a message in slack.

inputs:
  bot-token:
    description: 'Specify the slack bot token.'
    required: true
  channel-id:
    channel-id: 'Specify the slack channel-id.'
    required: true
  message:
    description: |-
      Slack message on Markdown format. Multiline messages must be escaped using URL encoding.
      https://github.com/orgs/community/discussions/26288

      This is an example how to escape a multiline message in Python:
      <pre>from urllib.parse import quote

      message = quote("""
      Hello!!!
      This is a multiline message
      """) # Multiline message</pre>
    required: true
  thread-timestamp:
    description: If you want to post a message as a threaded reply
    required: false
outputs:
  thread-timestamp:
    description: 'The timestamp on the message that was posted into Slack when using bot token'
    value: ${{ steps.slack_message.outputs.ts }}
runs:
  using: composite
  steps:
    - name: prepare message
      shell: python
      id: prepare
      env:
        MESSAGE: ${{ inputs.message }}
      run: |
        # Prepare Slack API payload.
        # Documentation about the payload format.
        # https://api.slack.com/reference/messaging/payload
        # https://app.slack.com/block-kit-builder
        # https://api.slack.com/reference/surfaces/formatting
        # https://api.slack.com/reference/surfaces/formatting#escaping
        import os
        from urllib.parse import unquote
        import json

        if os.environ["MESSAGE"]:
          message = os.environ.get('MESSAGE', 'No message')
          message = unquote(message)
          message = '\n'.join(line.strip() for line in message.splitlines())
        else:
          raise Exception("message must be set.")

        # Escape special characters for GitHub Actions output
        message = message.replace('\n', '\\n').replace('\r', '\\r')

        print("message is: ${message}")
        sanitizedMessage = json.dumps(message)
        print("sanitized message is: ${sanitizedMessage}")

        with open(os.environ.get('GITHUB_OUTPUT'), "a") as f:
          f.write("message={}".format(sanitizedMessage))

    - uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
      id: slack_message
      with:
        method: chat.postMessage
        token: ${{ inputs.bot-token }}
        payload: |
          unfurl_links: false
          unfurl_media: false
          channel: "${{ inputs.channel-id }}"
          thread_ts: "${{ inputs.thread-timestamp }}"
          text: "${{ steps.prepare.outputs.message }}"
          blocks:
            - type: "section"
              text:
                type: mrkdwn
                text: "${{ steps.prepare.outputs.message }}"
