name: 'oblt-cli/cluster-credentials'
description: 'Run the oblt-cli wrapper to retrieve the credentials to connect to the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  cluster-info-file:
    description: 'The cluster info file (absolute path)'
    required: false
  github-token:
    description: 'The GitHub access token.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: elastic/oblt-actions/oblt-cli/cluster-name-validation@v1.12.1
      id: validation
      with:
        cluster-name: ${{ inputs.cluster-name }}
        cluster-info-file: ${{ inputs.cluster-info-file }}

    - uses: elastic/oblt-actions/oblt-cli/setup@v1.12.1
      with:
        github-token: ${{ inputs.github-token }}

    - name: run oblt-cli
      run: |
        oblt-cli cluster secrets env --cluster-name "${{ steps.validation.outputs.cluster-name }}" --output-file "${{ env.ENV_FILE }}"
        cat "${{ env.ENV_FILE }}" >> "${GITHUB_ENV}"
        source "${{ env.ENV_FILE }}"
        for i in $(cat "${{ env.ENV_FILE }}"|cut -d "=" -f 1); do
          VALUE=$(eval "echo \${$i}")
          if [ -n "$VALUE" ] ; then
            echo "::add-mask::${VALUE}"
          fi
        done
        rm -f "${{ env.ENV_FILE }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ENV_FILE: ${{ runner.temp }}/.cluster-credentials
