name: updatecli/run-notify
description: |
  This is an opinionated GitHub Action to run the updatecli with some slack
  notifications.
inputs:
  command:
    description: 'Specify the updatecli command to be executed.'
    required: true
  slack-channel-id:
    channel-id: 'Specify the slack channel-id.'
    required: true
  slack-bot-token:
    description: 'Specify the slack bot token.'
    required: true
  slack-message:
    description: 'Specify the message to be sent (markdown format).'
    required: true
  slack-send-when:
    description: 'When to send the message, always, failure, success.'
    default: 'failure'
    required: false
runs:
  using: composite
  steps:
    - uses: elastic/oblt-actions/updatecli/run@v1
      with:
        command: ${{ inputs.command }}

    - if: ${{ always() && inputs.slack-send-when == 'always' }}
      uses: elastic/oblt-actions/slack/send@v1
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        bot-token: ${{ inputs.slack-bot-token }}
        message: ${{ inputs.slack-message }}

    - if: ${{ failure() && inputs.slack-send-when == 'failure' }}
      uses: elastic/oblt-actions/slack/send@v1
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        bot-token: ${{ inputs.slack-bot-token }}
        message: ${{ inputs.slack-message }}

    - if: ${{ success() && inputs.slack-send-when == 'success' }}
      uses: elastic/oblt-actions/slack/send@v1
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        bot-token: ${{ inputs.slack-bot-token }}
        message: ${{ inputs.slack-message }}
