name: 'github/is-member-of'

description: Check whether the given GitHub user is a member of the given GitHub organization

inputs:
  github-user:
    description: 'The GitHub user'
    required: true
  github-org:
    description: 'The GitHub org'
    required: true
  github-token:
    description: 'The GitHub access token'
    required: true
  exclude-bots:
    description: 'Exclude bots'
    default: 'true'
    required: false

outputs:
  result:
    description: 'The result in either true or false'
    value: ${{ steps.gh-api-is-member.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: gh-api-is-member
      name: Check if user is member of the given org
      run: |
        user_type="$(gh api -H 'Accept: application/vnd.github+json' /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} --jq '.user.type' )"
        result='false'
        if [ '' != "${user_type}" ]; then
          result='true'
        fi
        if [ 'true' == "${{ env.EXCLUDE_BOTS }}" ]; then
          if [ 'Bot' == "${user_type}" ]; then
            result='false'
          fi
        fi
        echo "result=${result}" >> $GITHUB_OUTPUT
      env:
        EXCLUDE_BOTS: ${{ inputs.exclude-bots }}
        GH_TOKEN: ${{ inputs.github-token }}
        GH_USER: ${{ inputs.github-user }}
        GH_ORG: ${{ inputs.github-org }}
      shell: bash
