name: 'github/is-member-of'

description: Check whether the given GitHub user is a member of the given GitHub organization.

inputs:
  github-user:
    description: 'The GitHub user'
    required: true
  github-org:
    description: 'The GitHub org'
    required: true
  github-token:
    description: 'The GitHub access token'
    required: true

outputs:
  result:
    description: '`true` if user is member of the GitHub org, `false` if not a member or a bot'
    value: ${{ steps.gh-api-is-member.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: gh-api-is-member
      name: Check if user is member of the given org
      run: |
        # required because 'gh api' will return non-zero for 404s to indicate lack of membership
        set +e
        # gh api will return a 404 with status to indicate lack of membership
        result=$(gh api \
          -H "Accept: application/vnd.github+json" \
          /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} 2>/dev/null | jq -r '.status // "member"' )

        if [[ '404' != "${result}" ]]; then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          # 404 or unknown user type
          echo "result=false" >> $GITHUB_OUTPUT
        fi
        set -e
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_USER: ${{ inputs.github-user }}
        GH_ORG: ${{ inputs.github-org }}
      shell: bash
