name: 'github/is-member-of'

description: Check whether the given GitHub user is a member of the given GitHub organization.

inputs:
  github-user:
    description: 'The GitHub user'
    required: true
  github-org:
    description: 'The GitHub org'
    required: true
  github-token:
    description: 'The GitHub access token'
    required: true

outputs:
  result:
    description: '`true` if user is member of the GitHub org, `false` if not a member or a bot'
    value: ${{ steps.gh-api-is-member.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: gh-api-is-member
      name: Check if user is member of the given org
      run: |
        # GH API call will return a 404 for non-members or bots
        set -e
        gh api -H 'Accept: application/vnd.github+json' /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} --jq . 
        
        user_type=$(gh api -H 'Accept: application/vnd.github+json' /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} --jq .user.type 2>/dev/null)
        set +e
        if [ 'User' != "${user_type}" ]; then
          result='true'
        else
          result='false'
        fi
        echo "result=${result}" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_USER: ${{ inputs.github-user }}
        GH_ORG: ${{ inputs.github-org }}
      shell: bash
