name: no-test

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!.github/workflows/test-*'
      - '!aws/auth/**'
      - '!azure/auth/**'
      - '!buildkite/flaky-report/**'
      - '!buildkite/run/**'
      - '!check-dependent-jobs/**'
      - '!download-kibana-dashboard/**'
      - '!elastic/github-commands/**'
      - '!elastic/validate-catalog/**'
      - '!feature-freeze/**'
      - '!git/setup/**'
      - '!github/backport-active/**'
      - '!github/changed-files/**'
      - '!github/create-token/**'
      - '!github/project-add/**'
      - '!github/project-field-set/**'
      - '!github/user-type/**'
      - '!google/auth/**'
      - '!oblt-cli/cluster-name-validation/**'
      - '!oblt-cli/list/**'
      - '!oblt-cli/run/**'
      - '!pre-commit/**'
      - '!updatecli/run/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - run: echo "No test to run"

  notify-fork:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - name: Warn about fork
        run: echo "::warning::In order to run this workflow you must create a feature branch in the main repo."
      - name: Notify PR about fork
        uses: edumserrano/find-create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- elastic/oblt-actions/notify-fork -->'
          comment-author: 'github-actions[bot]'
          edit-mode: replace
          body: |
            <!-- elastic/oblt-actions/notify-fork -->
            ## :warning: Fork detected

            This pull request is from a fork. In order to run the e2e tests, you must create a feature branch in the main repository.
            Forks are not supported for running the e2e tests.
