name: test-github-backport-active

on:
  merge_group: ~
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: true
        default: false
        type: boolean
  push:
    paths:
      - '.github/workflows/test-github-backport-active.yml'
      - 'github/backport-active/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  test-backport-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Test the action with backport-active-8 label
      - name: Test with backport-active-8
        uses: ./github/backport-active
        with:
          backports-url: "https://raw.githubusercontent.com/example-org/example-repo/main/branches-config.json"
          dry-run: 'true'
          test-pr-number: '9998'
          test-pr-labels: 'backport-active-8'

      # Test the action with backport-active-9 label
      - name: Test with backport-active-9
        uses: ./github/backport-active
        with:
          backports-url: "https://raw.githubusercontent.com/example-org/example-repo/main/branches-config.json"
          dry-run: 'true'
          test-pr-number: '9999'
          test-pr-labels: 'backport-active-9'

      # Test the action with backport-active-all label
      - name: Test with backport-active-all
        uses: ./github/backport-active
        with:
          backports-url: "https://raw.githubusercontent.com/example-org/example-repo/main/branches-config.json"
          dry-run: 'true'
          test-pr-number: '10000'
          test-pr-labels: 'backport-active-all'

      # Test with multiple labels
      - name: Test with multiple labels
        uses: ./github/backport-active
        with:
          backports-url: "https://raw.githubusercontent.com/example-org/example-repo/main/branches-config.json"
          dry-run: 'true'
          test-pr-number: '10001'
          test-pr-labels: 'backport-active-8,backport-active-9'
