name: test-aws-auth

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
    paths:
      - 'aws/auth/**'
      - '.github/workflows/test-aws-auth.yml'
  push:
    branches:
      - main
    paths:
      - 'aws/auth/**'
      - '.github/workflows/test-aws-auth.yml'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./aws/auth
        with:
          aws-region: us-east-1
      - run: aws sts get-caller-identity
