name: test-github-backport-active

on:
  merge_group: ~
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: true
        default: true
        type: boolean
  push:
    paths:
      - '.github/workflows/test-github-backport-active.yml'
      - 'github/backport-active/**'

permissions:
  contents: read

jobs:
  test:
    needs:
      - backport-action
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: elastic/oblt-actions/check-dependent-jobs@v1
        with:
          jobs: ${{ toJSON(needs) }}
      - run: ${{ steps.check.outputs.is-success }}

  backport-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test with actual PR info if available
      - name: Test with actual PR info
        if: github.event_name == 'pull_request'
        uses: ./github/backport-active
        with:
          backports-url: "https://storage.googleapis.com/artifacts-api/snapshots/branches.json"
          dry-run: true
          test-pr-number: ${{ github.event.pull_request.number }}
          test-pr-labels: ${{ join(github.event.pull_request.labels.*.name, ',') }}

      # Test the action with backport-active-8 label
      - name: Test with backport-active-8
        uses: ./github/backport-active
        with:
          backports-url: "https://storage.googleapis.com/artifacts-api/snapshots/branches.json"
          dry-run: ${{ github.event.inputs.dry-run }}
          test-pr-number: 9998
          test-pr-labels: 'backport-active-8'

      # Test the action with backport-active-9 label
      - name: Test with backport-active-9
        uses: ./github/backport-active
        with:
          backports-url: "https://storage.googleapis.com/artifacts-api/snapshots/branches.json"
          dry-run: ${{ github.event.inputs.dry-run }}
          test-pr-number: 9999
          test-pr-labels: 'backport-active-9'

      # Test the action with backport-active-all label
      - name: Test with backport-active-all
        uses: ./github/backport-active
        with:
          backports-url: "https://storage.googleapis.com/artifacts-api/snapshots/branches.json"
          dry-run: ${{ github.event.inputs.dry-run }}
          test-pr-number: 10000
          test-pr-labels: 'backport-active-all'

      # Test with multiple labels
      - name: Test with multiple labels
        uses: ./github/backport-active
        with:
          backports-url: "https://storage.googleapis.com/artifacts-api/snapshots/branches.json"
          dry-run: ${{ github.event.inputs.dry-run }}
          test-pr-number: 10001
          test-pr-labels: 'backport-active-8,backport-active-9'
