name: test-github-notify-pr-is-fork

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-github-notify-pr-is-fork.yml'
      - 'github/notify-pr-is-fork/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-github-notify-pr-is-fork.yml'
      - 'github/notify-pr-is-fork/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: ./github/notify-pr-is-fork
