name: test-google-auth

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-google-auth.yml'
      - 'google/auth/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-google-auth.yml'
      - 'google/auth/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./google/auth
        id: google-auth
        continue-on-error: true
        with:
          repository: elastic/dummy
      - run: >
          test
          "projects/8560181848/locations/global/workloadIdentityPools/github/providers/repo-37af2ab116595bd21e72f6b8478"
          =
          "${{ steps.google-auth.outputs.workload-identity-provider }}"
