name: test-elastic-token
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'elastic/github-token/**'
      - '.github/workflows/test-elastic-github-token.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./elastic/github-token
