name: test-elastic-gscm-secrets

on:
  merge_group: ~
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-elastic-gscm-secrets.yml'
      - 'elastic/gscm-secrets/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-elastic-gscm-secrets.yml'
      - 'elastic/gscm-secrets/**'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./elastic/gscm-secrets
        with:
          oblt-cluster: observability-ci
      - name: Assert credentials were exported
        run: |
          test -n "${ELASTICSEARCH_HOST}"
          test -n "${ELASTICSEARCH_USERNAME}"
          test -n "${ELASTICSEARCH_PASSWORD}"
          test -n "${KIBANA_HOST}"
          test -n "${KIBANA_USERNAME}"
          test -n "${KIBANA_PASSWORD}"
