name: test-oblt-cli-cluster-name-validation-cluster-name

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-oblt-cli-cluster-name-validation.yml'
      - 'oblt-cli/cluster-name-validation/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-oblt-cli-cluster-name-validation.yml'
      - 'oblt-cli/cluster-name-validation/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./oblt-cli/cluster-name-validation
        id: validation
        with:
          cluster-name: 'foo'
      - name: Assert is foo
        run: test "${{steps.validation.outputs.cluster-name}}" = "foo"
